# Generated by Django 4.2.8 on 2023-12-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
