# Generated by Django 4.2.8 on 2023-12-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0002_rename_last_name_teammember_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='lastName',
            new_name='location',
        ),
    ]
