# Generated by Django 4.2.8 on 2023-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManage', '0003_rename_lastname_teammember_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='TeamManage',
        ),
    ]
